# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20161219_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='ignore_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
