# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_taskcondition_ignore_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='operation',
        ),
    ]
