# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0004_remove_task_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
