# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0006_auto_20161222_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='task',
            name='expected',
        ),
        migrations.AddField(
            model_name='sensortask',
            name='actual',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensortask',
            name='expected',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
