# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_auto_20170110_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Sensor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Task')),
            ],
        ),
    ]
