# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0011_excludesensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='ip',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='database',
            name='type',
            field=models.CharField(choices=[('Q', 'MQTT'), ('G', 'MongoDB'), ('S', 'MySQL'), ('U', 'UDP Proxy'), ('I', 'Iqlect Server')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('E', 'Event Based'), ('D', 'Daily'), ('H', 'Hourly'), ('5', 'Every 5 Minutes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='taskcondition',
            name='condition',
            field=models.CharField(choices=[('=', '=='), ('!', '!='), ('<', '<'), ('L', '<='), ('>', '>'), ('G', '>='), ('C', 'Count'), ('I', 'Increment By'), ('S', 'Sting is same'), ('T', 'Sting is Not same')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='excludesensor',
            unique_together=set([('task', 'sensor')]),
        ),
    ]
