# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0012_auto_20170123_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorchannel',
            name='channel',
            field=models.CharField(choices=[('data', 'Data'), ('H', 'Hartbeat'), ('info', 'Sensor information'), ('nodemcu', 'nodemcu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sensordatabase',
            name='purpose',
            field=models.CharField(choices=[('P', 'Primary Storage'), ('B', 'Primary Broker'), ('L', 'Local Broker'), ('R', 'Iqlect Rest API')], max_length=1),
        ),
    ]
