# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0013_auto_20170214_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='public_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
