# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0014_sensor_public_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorchannel',
            name='display_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
